// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyurbfticalpkbjtuzqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5dXJiZnRpY2FscGtianR1enFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODc4MTUsImV4cCI6MjA2ODI2MzgxNX0.Ib8P0puXY3EVRTU5ossduqcrSWr4lW_tKYneO4Kwhu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});